-- AUTO-GENERATED by scripts/generate-seed.mjs — do not hand-edit hashes.
-- Re-run `npm run seed:hash` if you change any initial password above.

INSERT INTO users (username, password_hash, password_salt, role, display_name, active, must_change_password) VALUES ('Teamleader', '31e43080516fe210e1bc71b91a557db8f565c748f99d0a8334b563149a8c2d99', '90b936cf52a54ac4ebf83c632abd2efa', 'team_leader', 'Team Leader', 1, 1) ON CONFLICT(username) DO NOTHING;
INSERT INTO users (username, password_hash, password_salt, role, display_name, active, must_change_password) VALUES ('Ashrakat', 'bf60790aba46739b9a3d31c51cdc86cb5aa751f07a1b94fc8e0782c173d9fb6a', '4abe9a0e54cbc3128a16461720f14624', 'employee', 'Ashrakat', 1, 1) ON CONFLICT(username) DO NOTHING;
INSERT INTO users (username, password_hash, password_salt, role, display_name, active, must_change_password) VALUES ('Menna', 'c941865885b039a782608ee56a126d5e2d1f5eb6de1a8e15963ff51a38175e6d', 'ffab29a87701995e6d0a7a5f514f1720', 'employee', 'Menna', 1, 1) ON CONFLICT(username) DO NOTHING;
INSERT INTO users (username, password_hash, password_salt, role, display_name, active, must_change_password) VALUES ('Huda', '3b97a0638c296f4e7bdacc9763ffa04f970bc7b971e5d9807d0208604de184b8', 'f39117f80ac75642bb6d6f144fd41735', 'employee', 'Huda', 1, 1) ON CONFLICT(username) DO NOTHING;
INSERT INTO users (username, password_hash, password_salt, role, display_name, active, must_change_password) VALUES ('Rahma', '0a06c2ff3032904eb7e8975e6ef391c424eafdce2af362001548e21761d3da09', '01c1d5c7e0b22ddde4d787f4cd17dbfe', 'employee', 'Rahma', 1, 1) ON CONFLICT(username) DO NOTHING;
INSERT INTO users (username, password_hash, password_salt, role, display_name, active, must_change_password) VALUES ('Shimaa', 'e3f95205065bc4b6df59f351afa8dff43af5d69be0b1547945380e2565863cca', 'b01a507128e44b029bb9eb182208dbdb', 'employee', 'Shimaa', 1, 1) ON CONFLICT(username) DO NOTHING;

-- Create employee profile rows (with explicit Arabic display names).
INSERT INTO employees (user_id, name, name_ar, avatar_initial, availability, active)
SELECT u.id, 'Ashrakat', 'أشرقت', 'A', 'AVAILABLE', 1
FROM users u WHERE u.username = 'Ashrakat'
  AND NOT EXISTS (SELECT 1 FROM employees e WHERE e.user_id = u.id);
INSERT INTO employees (user_id, name, name_ar, avatar_initial, availability, active)
SELECT u.id, 'Menna', 'منة', 'M', 'AVAILABLE', 1
FROM users u WHERE u.username = 'Menna'
  AND NOT EXISTS (SELECT 1 FROM employees e WHERE e.user_id = u.id);
INSERT INTO employees (user_id, name, name_ar, avatar_initial, availability, active)
SELECT u.id, 'Huda', 'هدى', 'H', 'AVAILABLE', 1
FROM users u WHERE u.username = 'Huda'
  AND NOT EXISTS (SELECT 1 FROM employees e WHERE e.user_id = u.id);
INSERT INTO employees (user_id, name, name_ar, avatar_initial, availability, active)
SELECT u.id, 'Rahma', 'رحمة', 'R', 'AVAILABLE', 1
FROM users u WHERE u.username = 'Rahma'
  AND NOT EXISTS (SELECT 1 FROM employees e WHERE e.user_id = u.id);
INSERT INTO employees (user_id, name, name_ar, avatar_initial, availability, active)
SELECT u.id, 'Shimaa', 'شيماء', 'S', 'AVAILABLE', 1
FROM users u WHERE u.username = 'Shimaa'
  AND NOT EXISTS (SELECT 1 FROM employees e WHERE e.user_id = u.id);

-- Default settings (performance weights, distribution defaults).
INSERT INTO settings (key, value) VALUES ('performance_weights', '{"completionRate":0.35,"closedCustomers":0.30,"followupCompletion":0.20,"responseSpeed":0.15,"overduePenaltyPerItem":2}') ON CONFLICT(key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('distribution_defaults', '{"method":"EQUAL","onlyAvailableEmployees":true}') ON CONFLICT(key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('notification_prefs', '{"assignment":true,"followupDue":true,"followupOverdue":true,"reassignment":true}') ON CONFLICT(key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('whatsapp_template', '{"template":"أهلاً بحضرتك {{customer_name}} 🌷\nمع حضرتك {{employee_name}} من {{company_name}}.\nحاولنا التواصل مع حضرتك هاتفيًا، ويسعدنا تواصلك معنا عند رؤيتك للرسالة.\nيسعدنا تواصلك معنا في الوقت المناسب لحضرتك.\nنتمنى لحضرتك يومًا سعيدًا 🌷\n{{company_name}}","companyName":"رحمة مول"}') ON CONFLICT(key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('sla_rules', '{"seenWithinMinutes":10,"contactWithinMinutesAfterSeen":15,"followupWithinMinutesAfterInterested":60}') ON CONFLICT(key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('lead_score_weights', '{"interested":25,"contacted":15,"followupScheduled":10,"whatsappInteraction":12,"recentActivityBonus":18,"closedWon":20,"callAttemptPenalty":-3,"noAnswerStreakPenalty":-5,"slaBreachPenalty":-8}') ON CONFLICT(key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('presence_thresholds', '{"idleAfterMinutes":5,"offlineAfterMinutesNoHeartbeat":15}') ON CONFLICT(key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('sales_settings', '{"taxRatePercent":0,"paymentMethods":["CASH","CARD","INSTALLMENT","OTHER"]}') ON CONFLICT(key) DO NOTHING;
