-- AUTO-GENERATED by scripts/generate-seed.mjs — do not hand-edit hashes.
-- Re-run `npm run seed:hash` if you change any initial password above.

INSERT INTO users (username, password_hash, password_salt, role, display_name, active, must_change_password) VALUES ('Teamleader', 'ed36972705144b435623d6a3ebda9cc43ccfeaad5b0e5a2a74df0cb4574aa9db', '5509ee894166904c36d3309a9df029c6', 'team_leader', 'Team Leader', 1, 1) ON CONFLICT(username) DO NOTHING;
INSERT INTO users (username, password_hash, password_salt, role, display_name, active, must_change_password) VALUES ('Ashrakat', '656a9d69b493741c72c489549a813c405483a2dc30288c5a41057437d7f80bf0', '841a54c27927dd6484cd6c414837d7b0', 'employee', 'Ashrakat', 1, 1) ON CONFLICT(username) DO NOTHING;
INSERT INTO users (username, password_hash, password_salt, role, display_name, active, must_change_password) VALUES ('Menna', 'd63533c82bb4b6af73e8cd8d085e14d2f1ec287b9d192542faa47c1c00ae06bf', '0cf19c55556e7705141fd1d12c9db578', 'employee', 'Menna', 1, 1) ON CONFLICT(username) DO NOTHING;
INSERT INTO users (username, password_hash, password_salt, role, display_name, active, must_change_password) VALUES ('Huda', '513eb9b734f4286303cd0b52a051a2fbd3c4b146dd63f69e372950c645888e8a', '871e5bea3d1527429b9c08c2b077dd9a', 'employee', 'Huda', 1, 1) ON CONFLICT(username) DO NOTHING;
INSERT INTO users (username, password_hash, password_salt, role, display_name, active, must_change_password) VALUES ('Rahma', '3c1c6674ff037a088319150e7672beae9ab94019274f5febe5e38adfa239d9f4', '946ffa5d593dc83155c4f540fe148f36', 'employee', 'Rahma', 1, 1) ON CONFLICT(username) DO NOTHING;
INSERT INTO users (username, password_hash, password_salt, role, display_name, active, must_change_password) VALUES ('Shimaa', '5b2e46ba0ae120b9721f8440a2962b8bd8b8bdb8f98d9d332cb16e4457013913', '50ce2d66c99b1b38c27fc839fb9f1d82', 'employee', 'Shimaa', 1, 1) ON CONFLICT(username) DO NOTHING;

-- Create employee profile rows (with explicit Arabic display names).
INSERT INTO employees (user_id, name, name_ar, avatar_initial, availability, active)
SELECT u.id, 'Ashrakat', 'أشرقت', 'A', 'AVAILABLE', 1
FROM users u WHERE u.username = 'Ashrakat'
  AND NOT EXISTS (SELECT 1 FROM employees e WHERE e.user_id = u.id);
INSERT INTO employees (user_id, name, name_ar, avatar_initial, availability, active)
SELECT u.id, 'Menna', 'منة', 'M', 'AVAILABLE', 1
FROM users u WHERE u.username = 'Menna'
  AND NOT EXISTS (SELECT 1 FROM employees e WHERE e.user_id = u.id);
INSERT INTO employees (user_id, name, name_ar, avatar_initial, availability, active)
SELECT u.id, 'Huda', 'هدى', 'H', 'AVAILABLE', 1
FROM users u WHERE u.username = 'Huda'
  AND NOT EXISTS (SELECT 1 FROM employees e WHERE e.user_id = u.id);
INSERT INTO employees (user_id, name, name_ar, avatar_initial, availability, active)
SELECT u.id, 'Rahma', 'رحمة', 'R', 'AVAILABLE', 1
FROM users u WHERE u.username = 'Rahma'
  AND NOT EXISTS (SELECT 1 FROM employees e WHERE e.user_id = u.id);
INSERT INTO employees (user_id, name, name_ar, avatar_initial, availability, active)
SELECT u.id, 'Shimaa', 'شيماء', 'S', 'AVAILABLE', 1
FROM users u WHERE u.username = 'Shimaa'
  AND NOT EXISTS (SELECT 1 FROM employees e WHERE e.user_id = u.id);

-- Default settings (performance weights, distribution defaults).
INSERT INTO settings (key, value) VALUES ('performance_weights', '{"completionRate":0.35,"closedCustomers":0.30,"followupCompletion":0.20,"responseSpeed":0.15,"overduePenaltyPerItem":2}') ON CONFLICT(key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('distribution_defaults', '{"method":"EQUAL","onlyAvailableEmployees":true}') ON CONFLICT(key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('notification_prefs', '{"assignment":true,"followupDue":true,"followupOverdue":true,"reassignment":true}') ON CONFLICT(key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('whatsapp_template', '{"template":"أهلاً بحضرتك {{customer_name}} 🌷\nمع حضرتك {{employee_name}} من {{company_name}}.\nحاولنا التواصل مع حضرتك هاتفيًا، ويسعدنا تواصلك معنا عند رؤيتك للرسالة.\nيسعدنا تواصلك معنا في الوقت المناسب لحضرتك.\nنتمنى لحضرتك يومًا سعيدًا 🌷\n{{company_name}}","companyName":"رحمة مول"}') ON CONFLICT(key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('sla_rules', '{"seenWithinMinutes":10,"contactWithinMinutesAfterSeen":15,"followupWithinMinutesAfterInterested":60}') ON CONFLICT(key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('lead_score_weights', '{"interested":25,"contacted":15,"followupScheduled":10,"whatsappInteraction":12,"recentActivityBonus":18,"closedWon":20,"callAttemptPenalty":-3,"noAnswerStreakPenalty":-5,"slaBreachPenalty":-8}') ON CONFLICT(key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('presence_thresholds', '{"idleAfterMinutes":5,"offlineAfterMinutesNoHeartbeat":15}') ON CONFLICT(key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('sales_settings', '{"taxRatePercent":0,"paymentMethods":["CASH","CARD","INSTALLMENT","OTHER"]}') ON CONFLICT(key) DO NOTHING;
