// Generates worker/migrations/seed.sql with the 6 initial accounts.
// Passwords are hashed here (PBKDF2-SHA256, same algorithm the Worker uses
// to verify at login) — plaintext never reaches D1 or any committed file
// beyond this list, which the project owner is expected to rotate after
// first login (see README "Initial user setup").
import { writeFileSync } from 'node:fs';
import { hashPassword, randomSaltHex } from '../worker/src/lib/passwords.js';

// nameAr is stored explicitly per section 3 of the WhatsApp feature spec —
// it is never auto-transliterated/translated from the English name.
const ACCOUNTS = [
  { username: 'Teamleader', password: 'Rahmamallofficial199978518', role: 'team_leader', name: 'Team Leader', nameAr: null },
  { username: 'Ashrakat', password: 'Ashrakat1559', role: 'employee', name: 'Ashrakat', nameAr: 'أشرقت' },
  { username: 'Menna', password: 'Menna1009', role: 'employee', name: 'Menna', nameAr: 'منة' },
  { username: 'Huda', password: 'Huda1579', role: 'employee', name: 'Huda', nameAr: 'هدى' },
  { username: 'Rahma', password: 'Rahma1669', role: 'employee', name: 'Rahma', nameAr: 'رحمة' },
  { username: 'Shimaa', password: 'Shimaa1772', role: 'employee', name: 'Shimaa', nameAr: 'شيماء' },
];

function esc(s) {
  return String(s).replace(/'/g, "''");
}

const lines = [];
lines.push('-- AUTO-GENERATED by scripts/generate-seed.mjs — do not hand-edit hashes.');
lines.push('-- Re-run `npm run seed:hash` if you change any initial password above.');
lines.push('');

for (const acc of ACCOUNTS) {
  const salt = randomSaltHex();
  const hash = await hashPassword(acc.password, salt);
  const mustChange = 1; // force password rotation on first login in production
  lines.push(
    `INSERT INTO users (username, password_hash, password_salt, role, display_name, active, must_change_password) VALUES ('${esc(
      acc.username
    )}', '${hash}', '${salt}', '${acc.role}', '${esc(acc.name)}', 1, ${mustChange}) ON CONFLICT(username) DO NOTHING;`
  );
}
lines.push('');
lines.push('-- Create employee profile rows (with explicit Arabic display names).');
for (const acc of ACCOUNTS) {
  if (acc.role !== 'employee') continue;
  lines.push(
    `INSERT INTO employees (user_id, name, name_ar, avatar_initial, availability, active)
SELECT u.id, '${esc(acc.name)}', ${acc.nameAr ? `'${esc(acc.nameAr)}'` : 'NULL'}, '${esc(acc.name[0].toUpperCase())}', 'AVAILABLE', 1
FROM users u WHERE u.username = '${esc(acc.username)}'
  AND NOT EXISTS (SELECT 1 FROM employees e WHERE e.user_id = u.id);`
  );
}

lines.push('');
lines.push('-- Default settings (performance weights, distribution defaults).');
lines.push(`INSERT INTO settings (key, value) VALUES ('performance_weights', '{"completionRate":0.35,"closedCustomers":0.30,"followupCompletion":0.20,"responseSpeed":0.15,"overduePenaltyPerItem":2}') ON CONFLICT(key) DO NOTHING;`);
lines.push(`INSERT INTO settings (key, value) VALUES ('distribution_defaults', '{"method":"EQUAL","onlyAvailableEmployees":true}') ON CONFLICT(key) DO NOTHING;`);
lines.push(`INSERT INTO settings (key, value) VALUES ('notification_prefs', '{"assignment":true,"followupDue":true,"followupOverdue":true,"reassignment":true}') ON CONFLICT(key) DO NOTHING;`);

const defaultWhatsappTemplate = [
  'أهلاً بحضرتك {{customer_name}} 🌷',
  'مع حضرتك {{employee_name}} من {{company_name}}.',
  'حاولنا التواصل مع حضرتك هاتفيًا، ويسعدنا تواصلك معنا عند رؤيتك للرسالة.',
  'يسعدنا تواصلك معنا في الوقت المناسب لحضرتك.',
  'نتمنى لحضرتك يومًا سعيدًا 🌷',
  '{{company_name}}',
].join('\n');
lines.push(
  `INSERT INTO settings (key, value) VALUES ('whatsapp_template', '${esc(
    JSON.stringify({ template: defaultWhatsappTemplate, companyName: 'رحمة مول' })
  )}') ON CONFLICT(key) DO NOTHING;`
);

// --- Master upgrade defaults: SLA thresholds, lead score weights, presence timing.
lines.push(`INSERT INTO settings (key, value) VALUES ('sla_rules', '${esc(JSON.stringify({
  seenWithinMinutes: 10,
  contactWithinMinutesAfterSeen: 15,
  followupWithinMinutesAfterInterested: 60,
}))}') ON CONFLICT(key) DO NOTHING;`);
lines.push(`INSERT INTO settings (key, value) VALUES ('lead_score_weights', '${esc(JSON.stringify({
  interested: 25,
  contacted: 15,
  followupScheduled: 10,
  whatsappInteraction: 12,
  recentActivityBonus: 18,
  closedWon: 20,
  callAttemptPenalty: -3,
  noAnswerStreakPenalty: -5,
  slaBreachPenalty: -8,
}))}') ON CONFLICT(key) DO NOTHING;`);
lines.push(`INSERT INTO settings (key, value) VALUES ('presence_thresholds', '${esc(JSON.stringify({
  idleAfterMinutes: 5,
  offlineAfterMinutesNoHeartbeat: 15,
}))}') ON CONFLICT(key) DO NOTHING;`);
lines.push(`INSERT INTO settings (key, value) VALUES ('sales_settings', '${esc(JSON.stringify({
  taxRatePercent: 0,
  paymentMethods: ['CASH', 'CARD', 'INSTALLMENT', 'OTHER'],
}))}') ON CONFLICT(key) DO NOTHING;`);

writeFileSync(new URL('../worker/seed/seed.sql', import.meta.url), lines.join('\n') + '\n');
console.log('Wrote worker/seed/seed.sql for', ACCOUNTS.length, 'accounts.');
